fx_version "cerulean"
game "gta5"
name "qb-walter"
description "cocaine trade"
author "By Panther"
version "1.0.0"

shared_script "config.lua"
client_script "client.lua"
server_script "server.lua"